# Jekyll configuration for GitHub Pages
# This enables redirects from old WordPress URLs to new VitePress URLs

# Site settings
title: 'Shawon Notes'
description: 'Compiled resources for IGCSE and IAL to save your time'
url: 'https://shawonnotes.com'

# Jekyll plugins
plugins:
  - jekyll-redirect-from

# Redirects from old WordPress URLs to new VitePress URLs
redirects:
  # Homepage and main sections
  /index.php/igcse-edexcel-revision-notes/:
    redirect_to: /igcse/
  /index.php/edexcel-ial-revision-notes/:
    redirect_to: /ial/
  /index.php/edexcel-past-papers/:
    redirect_to: /igcse/past-papers/
  /index.php/edexcel-ial-past-papers/:
    redirect_to: /ial/past-papers/
  /index.php/edexcel-igcse-specifications/:
    redirect_to: /igcse/
  /index.php/edexcel-ial-specification/:
    redirect_to: /ial/
  /index.php/about/:
    redirect_to: /
  /index.php/contact-us/:
    redirect_to: /
  /index.php/404-error-page/:
    redirect_to: /
  /index.php/wpms-html-sitemap/:
    redirect_to: /

  # IGCSE Revision Notes
  /index.php/igcse-edexcel-revision-notes/chemistry/:
    redirect_to: /igcse/revision-notes/chemistry/
  /index.php/igcse-edexcel-revision-notes/biology/:
    redirect_to: /igcse/revision-notes/biology/
  /index.php/igcse-edexcel-revision-notes/physics/:
    redirect_to: /igcse/revision-notes/physics/
  /index.php/igcse-edexcel-revision-notes/mathematics-b/:
    redirect_to: /igcse/revision-notes/math-b/
  /index.php/igcse-edexcel-revision-notes/further-pure-mathematics/:
    redirect_to: /igcse/revision-notes/pure-math/
  /index.php/igcse-edexcel-revision-notes/ict/:
    redirect_to: /igcse/revision-notes/ict/

  # IAL Revision Notes
  /index.php/edexcel-ial-revision-notes/edexcel-ial-chemistry-revision-notes/:
    redirect_to: /ial/revision-notes/chemistry/
  /index.php/edexcel-ial-revision-notes/edexcel-ial-math-revision-notes/:
    redirect_to: /ial/revision-notes/math/
  /index.php/edexcel-ial-revision-notes/edexcel-ial-physics-revision-notes/:
    redirect_to: /ial/revision-notes/physics/

  # IGCSE Past Papers - Accounting
  /index.php/edexcel-past-papers/accounting/:
    redirect_to: /igcse/past-papers/accounting/
  /index.php/edexcel-past-papers/accounting/gce-o-level/:
    redirect_to: /igcse/past-papers/accounting/gce-o-level/
  /index.php/edexcel-past-papers/accounting/igcse/:
    redirect_to: /igcse/past-papers/accounting/igcse-from-2011/
  /index.php/edexcel-past-papers/accounting/international-gcse/:
    redirect_to: /igcse/past-papers/accounting/igcse-from-2017/

  # IGCSE Past Papers - Bengali
  /index.php/edexcel-past-papers/bengali/:
    redirect_to: /igcse/past-papers/bangla/
  /index.php/edexcel-past-papers/bengali/gce/:
    redirect_to: /igcse/past-papers/bangla/gce/
  /index.php/edexcel-past-papers/bengali/international-gcse/:
    redirect_to: /igcse/past-papers/bangla/igcse-from-2017/

  # IGCSE Past Papers - Biology
  /index.php/edexcel-past-papers/biology/:
    redirect_to: /igcse/past-papers/biology/
  /index.php/edexcel-past-papers/biology/gce-o-level/:
    redirect_to: /igcse/past-papers/biology/gce-o-level/
  /index.php/edexcel-past-papers/biology/igcse/:
    redirect_to: /igcse/past-papers/biology/igcse-from-2011/
  /index.php/edexcel-past-papers/biology/international-gcse/:
    redirect_to: /igcse/past-papers/biology/igcse-from-2017/

  # IGCSE Past Papers - Chemistry
  /index.php/edexcel-past-papers/chemistry/:
    redirect_to: /igcse/past-papers/chemistry/
  /index.php/edexcel-past-papers/chemistry/gce/:
    redirect_to: /igcse/past-papers/chemistry/gce/
  /index.php/edexcel-past-papers/chemistry/igcse/:
    redirect_to: /igcse/past-papers/chemistry/igcse-from-2011/
  /index.php/edexcel-past-papers/chemistry/international-gcse/:
    redirect_to: /igcse/past-papers/chemistry/igcse-from-2017/

  # IGCSE Past Papers - Economics
  /index.php/edexcel-past-papers/economics/:
    redirect_to: /igcse/past-papers/economics/
  /index.php/edexcel-past-papers/economics/gce-o-level/:
    redirect_to: /igcse/past-papers/economics/gce-o-level/
  /index.php/edexcel-past-papers/economics/international-gcse/:
    redirect_to: /igcse/past-papers/economics/igcse-from-2017/

  # IGCSE Past Papers - English Language B
  /index.php/edexcel-past-papers/english-language-b/:
    redirect_to: /igcse/past-papers/english-language-b/
  /index.php/edexcel-past-papers/english-language-b/gce-o-level/:
    redirect_to: /igcse/past-papers/english-language-b/gce-o-level/
  /index.php/edexcel-past-papers/english-language-b/international-gcse/:
    redirect_to: /igcse/past-papers/english-language-b/igcse-from-2017/

  # IGCSE Past Papers - Further Pure Mathematics
  /index.php/edexcel-past-papers/further-pure-mathematics/:
    redirect_to: /igcse/past-papers/further-pure-mathematics/
  /index.php/edexcel-past-papers/further-pure-mathematics/gce-o-level/:
    redirect_to: /igcse/past-papers/further-pure-mathematics/gce-o-level/
  /index.php/edexcel-past-papers/further-pure-mathematics/international-gcse/:
    redirect_to: /igcse/past-papers/further-pure-mathematics/igcse-from-2017/

  # IGCSE Past Papers - Human Biology
  /index.php/edexcel-past-papers/human-biology/:
    redirect_to: /igcse/past-papers/human-biology/
  /index.php/edexcel-past-papers/human-biology/gce-o-level/:
    redirect_to: /igcse/past-papers/human-biology/gce-o-level/
  /index.php/edexcel-past-papers/human-biology/international-gcse/:
    redirect_to: /igcse/past-papers/human-biology/igcse-from-2017/

  # IGCSE Past Papers - ICT
  /index.php/edexcel-past-papers/ict/:
    redirect_to: /igcse/past-papers/ict/
  /index.php/edexcel-past-papers/ict/gce-o-level/:
    redirect_to: /igcse/past-papers/ict/gce-o-level/
  /index.php/edexcel-past-papers/ict/igcse/:
    redirect_to: /igcse/past-papers/ict/igcse-from-2011/
  /index.php/edexcel-past-papers/ict/international-gcse/:
    redirect_to: /igcse/past-papers/ict/igcse-old/

  # IGCSE Past Papers - Mathematics B
  /index.php/edexcel-past-papers/mathematics-b/:
    redirect_to: /igcse/past-papers/mathematics-b/
  /index.php/edexcel-past-papers/mathematics-b/gce-o-level/:
    redirect_to: /igcse/past-papers/mathematics-b/gce-o-level/
  /index.php/edexcel-past-papers/mathematics-b/international-gcse/:
    redirect_to: /igcse/past-papers/mathematics-b/igcse-from-2017/

  # IGCSE Past Papers - Physics
  /index.php/edexcel-past-papers/physics/:
    redirect_to: /igcse/past-papers/physics/
  /index.php/edexcel-past-papers/physics/gce-o-level/:
    redirect_to: /igcse/past-papers/physics/gce-o-level/
  /index.php/edexcel-past-papers/physics/igcse/:
    redirect_to: /igcse/past-papers/physics/igcse-from-2011/
  /index.php/edexcel-past-papers/physics/igcse-2011/:
    redirect_to: /igcse/past-papers/physics/igcse-from-2011/

  # IAL Past Papers - Biology
  /index.php/edexcel-ial-past-papers/edexcel-as-ial-biology-past-papers/:
    redirect_to: /ial/past-papers/biology/

  # IAL Past Papers - Chemistry
  /index.php/edexcel-ial-past-papers/edexcel-as-ial-chemistry-past-papers/:
    redirect_to: /ial/past-papers/chemistry/

  # IAL Past Papers - Math
  /index.php/edexcel-ial-past-papers/edexcel-as-ial-math-past-papers/:
    redirect_to: /ial/past-papers/math/
  /index.php/edexcel-ial-past-papers/edexcel-as-ial-math-past-papers/edexcel-ial-c12-past-papers/:
    redirect_to: /ial/past-papers/math/c12/
  /index.php/edexcel-ial-past-papers/edexcel-as-ial-math-past-papers/edexcel-ial-c34-past-papers/:
    redirect_to: /ial/past-papers/math/c34/
  /index.php/edexcel-ial-past-papers/edexcel-as-ial-math-past-papers/edexcel-ial-m1-past-papers/:
    redirect_to: /ial/past-papers/math/m1/
  /index.php/edexcel-ial-past-papers/edexcel-as-ial-math-past-papers/edexcel-ial-s1-past-papers/:
    redirect_to: /ial/past-papers/math/s1/

  # IAL Past Papers - Physics
  /index.php/edexcel-ial-past-papers/edexcel-as-ial-physics-past-papers/:
    redirect_to: /ial/past-papers/physics/

# Build settings
markdown: kramdown
highlighter: rouge
